### ISSUE TITLE
Improve branched exception handling in vectorized ops

### ISSUE THREAD

**Issue by mike-gimelfarb** [pyrddlgym-project/pyRDDLGym#238]
Currently, a branched expression such as 

cpf(?x) = if(pvar(?x) == 0) then default(?x) else 1.0 / pvar(?x);

will raise a divide-by-zero exception such the 1.0 / pvar(?x) must be evaluated for all ?x regardless of the branch condition.
This is an unfortunate consequence of vectorized sampling. A current workaround is to call numpy.seterr(all='ignore') before simulation, but it is not a true fix.

We should try to fix this generally.

**Comment by ataitler** [comment]
Thanks Mike, I have seen the discussion :)

**Comment by mike-gimelfarb** [comment]
This issue will be automatically fixed by merging pyRDDLGym-v2-branch into main.
