### ISSUE TITLE
A function to get the grounded dict of non fluents

### ISSUE THREAD

**Issue by kasanari** [pyrddlgym-project/pyRDDLGym#263]
I am interested getting the values for each grounded non fluent term. As far as I am aware, there does not seem to be an straightforward way of obtaining this from the model, as `model.non_fluents` is a dictionary of lists that I would have to combine with object indices.

I noticed that the data structure I am interested in exists as an intermediary value in [model.py](https://github.com/pyrddlgym-project/pyRDDLGym/blob/main/pyRDDLGym/core/compiler/model.py) on line [992](https://github.com/pyrddlgym-project/pyRDDLGym/blob/b80bc67e6d8d01388e7054fa688198a15cdcc72c/pyRDDLGym/core/compiler/model.py#L992). Would it be possible to move the calculation of this variable into a separate function so that I can call it to get the data I want?

**Comment by mike-gimelfarb** [comment]
I suspect I may not fully understand your use case, but have you tried grounding the domain as described [here](https://pyrddlgym.readthedocs.io/en/latest/start2.html#grounding-a-domain)? You should be able to get the structure of grounded values and non-fluent grounded names if you call `model.non_fluents` on the grounded model, I think.

**Comment by kasanari** [comment]
`dict(env.model.ground_vars_with_values(model.non_fluents))` returned what I was seeking. Thank you for the information.

I had noticed the `ground_` functions, but I was unsure of their usage.
