### ISSUE TITLE
Allow python 3.12 for last releases of pyRDDLGym [feature-request]

### ISSUE THREAD

**Issue by nhuet** [pyrddlgym-project/pyRDDLGym#264]
I was not able to install last release (2.1) on a python 3.12 environment, and I see that this is a requirement written in setup.py.
As a consequence, I installed the previous one 2.0 (which does not seem to have an issue working with python 3.12), which in turns is not compatible with latest pyRDDLGym-rl release...

Why is it that 2.1 requires python<3.12?
Do you plan a release soon for python 3.12?

Many thanks.

**Comment by ataitler** [comment]
It is not a matter of v2.1 requires lower python than 3.12 and v2.0 dot not, and more that python changed some components such as casting in v3.12, which is incompatible with all of pyRDDLGym versions. So, in version 2.1 we added the restriction of using a lower version of python.

**Comment by mike-gimelfarb** [comment]
I'm thinking that at some point we will have to open compatibility with 3.12 and later python versions, regardless of whether numpy will fix that on their end.

**Comment by mike-gimelfarb** [comment]
Please check the latest PR. I am not sure I remember exactly what the problems were but one of them with casting was that numpy can_cast was causing a crash on latest version. I have fixed this particular issue, and the code seems to run correctly in a new python 3.12 environment.

**Comment by nhuet** [comment]
> It is not a matter of v2.1 requires lower python than 3.12 and v2.0 dot not, and more that python changed some components such as casting in v3.12, which is incompatible with all of pyRDDLGym versions. So, in version 2.1 we added the restriction of using a lower version of python.

We probably do not use the full extent of pyRDDLGym, but in the ci/cd process of our project [scikit-decide](https://github.com/airbus/scikit-decide), we do use pyRDDLGym on python 3.12 environments without any issues (this is still in a [PR](https://github.com/airbus/scikit-decide/pull/435) for now).

**Comment by mike-gimelfarb** [comment]
I believe the numpy casting checks were added sometime after v 2.0 was released, so is it possible you were testing on pyrddlgym 2.0? 2.1 does not work with python 3.12 on my end in a fresh environment.

**Comment by nhuet** [comment]
Yes  i was speaking about 2.0  (since pip installing 2.1 does not work because of the python<3.12 requirement)
